# Generated by Django 4.1.1 on 2022-11-18 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=1000)),
                ('template_details', models.TextField()),
                ('template_features', models.TextField()),
                ('template_layout', models.TextField()),
                ('template_price', models.IntegerField()),
                ('released_date', models.DateField(auto_now_add=True)),
                ('version', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=1000)),
                ('template_image', models.ImageField(null=True, upload_to='blog_images/')),
                ('template_url', models.URLField(default='#')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.tag')),
            ],
        ),
    ]
