# Generated by Django 3.2 on 2023-01-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('blog', models.TextField()),
                ('image', models.ImageField(upload_to='blogs_images/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='company_images/')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='partner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=10, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'percentage'), ('amount', 'amount')], default='percentage', max_length=100, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonial_images/')),
                ('company_name', models.CharField(max_length=100)),
                ('testimonial', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='order',
        ),
        migrations.RemoveField(
            model_name='template',
            name='released_date',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_featured',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_taxable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='template_files/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='template',
            name='tag',
        ),
        migrations.AddField(
            model_name='template',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='adminpanel.Tag'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_images/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category')),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category', models.CharField(max_length=100)),
                ('order', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.childcategory'),
        ),
        migrations.AddField(
            model_name='template',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subcategory'),
        ),
    ]
