# Generated by Django 4.1.1 on 2022-11-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_category_created_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_image',
            field=models.ImageField(null=True, upload_to='template_images/'),
        ),
    ]
