# Generated by Django 4.1.1 on 2022-11-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
