# Generated by Django 4.1.1 on 2022-11-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_template_tag_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_price',
            field=models.CharField(max_length=100),
        ),
    ]
