# Generated by Django 4.1.1 on 2022-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_template_template_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_url',
            field=models.URLField(default='/'),
        ),
    ]
