# Generated by Django 4.1.1 on 2022-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_subcategory_childcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='childcategory',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='childcategory',
            name='status',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
