# Generated by Django 4.1.1 on 2022-11-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_category_created_alter_childcategory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subcategory'),
        ),
    ]
