# Generated by Django 4.1.1 on 2022-11-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alter_childcategory_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.childcategory'),
        ),
        migrations.AddField(
            model_name='template',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subcategory'),
        ),
    ]
