# Generated by Django 4.1.1 on 2022-11-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_template_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='released_date',
        ),
        migrations.AlterField(
            model_name='template',
            name='template_price',
            field=models.IntegerField(max_length=100),
        ),
    ]
