# Generated by Django 4.1.1 on 2022-11-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_remove_template_released_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_price',
            field=models.IntegerField(),
        ),
    ]
