# Generated by Django 4.1.3 on 2022-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0017_alter_template_template_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="sub_category",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
