# Generated by Django 4.1.1 on 2022-11-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_alter_category_status_alter_childcategory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', null=True),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='status',
            field=models.IntegerField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.IntegerField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', null=True),
        ),
    ]
