# Generated by Django 4.1.1 on 2022-11-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_alter_category_status_alter_childcategory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_featured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, null=True),
        ),
    ]
