# Generated by Django 4.1.1 on 2022-11-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_template_is_featured_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='is_featured',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
