# Generated by Django 4.1.1 on 2022-11-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_alter_template_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_images/'),
        ),
    ]
