# Generated by Django 4.1.1 on 2022-11-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_blogs_companysetup_partner_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'percentage'), ('amount', 'amount')], default='percentage', max_length=100, null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
