# Generated by Django 4.1.1 on 2022-11-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_testimonial_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='companysetup',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100),
        ),
    ]
