# Generated by Django 3.2 on 2022-11-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_auto_20221129_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs_images/'),
        ),
    ]
