# Generated by Django 3.2 on 2022-11-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_taxable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20),
        ),
    ]
