# Generated by Django 3.2 on 2022-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0030_template_is_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
