# Generated by Django 3.2 on 2022-11-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0031_auto_20221130_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='promo_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
