# Generated by Django 3.2 on 2022-12-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0036_template_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='tag',
        ),
        migrations.AddField(
            model_name='template',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='adminpanel.Tag'),
        ),
    ]
