# Generated by Django 4.1.5 on 2023-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0037_auto_20221207_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Category'},
        ),
        migrations.AlterModelOptions(
            name='childcategory',
            options={'verbose_name_plural': '3. Child Category'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '2. Sub Category'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(),
        ),
    ]
