# Generated by Django 3.2 on 2023-01-05 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0002_auto_20230104_1335'),
        ('features', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.template'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
