# Generated by Django 4.1.1 on 2022-11-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
