# Generated by Django 3.2 on 2022-12-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_purchasesummary_purchasedtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesummary',
            name='payment_method',
            field=models.CharField(choices=[('khalti', 'khalti'), ('other', 'other')], default='khalti', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasesummary',
            name='total_amount',
            field=models.IntegerField(max_length=1000),
        ),
    ]
