# Generated by Django 3.2 on 2022-12-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
