# Generated by Django 3.2 on 2022-12-06 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesummary',
            name='total_amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(10)]),
        ),
    ]
