# Generated by Django 3.2 on 2022-12-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_alter_purchasesummary_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesummary',
            name='template',
        ),
        migrations.AddField(
            model_name='purchasedtemplate',
            name='order_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasesummary',
            name='order_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
