# Generated by Django 3.2 on 2022-12-06 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_auto_20221206_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesummary',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasesummary',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('khalti', 'khalti'), ('other', 'other')], default='khalti', max_length=100, null=True),
        ),
    ]
