# Generated by Django 3.2 on 2022-12-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_auto_20221206_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtemplate',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
