# Generated by Django 3.2 on 2022-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_alter_purchasedtemplate_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtemplate',
            name='download_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
