# Generated by Django 3.2 on 2022-12-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_purchasedtemplate_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtemplate',
            name='purchase_summary',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='features.purchasesummary'),
            preserve_default=False,
        ),
    ]
