# Generated by Django 3.2 on 2023-05-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0017_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('priority', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
