# Generated by Django 3.2 on 2023-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0019_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='about_meta_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='blogs_meta_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='contact_meta_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='home_meta_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='themes_meta_title',
            field=models.CharField(max_length=255),
        ),
    ]
